version: '3.9'

services:
  # Backend Service
  backend:
    build: ./backend
    container_name: paradox-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: paradox-redis
    ports:
      - "6379:6379"

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus
    container_name: paradox-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  # Grafana Dashboard
  grafana:
    image: grafana/grafana
    container_name: paradox-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
